# Generated by Django 4.2.1 on 2023-06-08 11:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='xarakteristika_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
