# Generated by Django 4.2.1 on 2023-06-08 11:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_product_name_uz_product_xarakteristika_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='xarakteristika_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='xarakteristika_uz',
        ),
        migrations.AddField(
            model_name='product',
            name='name_r',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_u',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='xarakteristika_r',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='xarakteristika_u',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
