# Generated by Django 4.2.1 on 2023-06-08 11:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_remove_product_name_ru_remove_product_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name_r',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_u',
        ),
        migrations.RemoveField(
            model_name='product',
            name='xarakteristika_r',
        ),
        migrations.RemoveField(
            model_name='product',
            name='xarakteristika_u',
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='xarakteristika_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
