# Generated by Django 4.2.1 on 2023-06-11 08:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_remove_product_name_r_remove_product_name_u_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='xarakteristika_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
