# Generated by Django 4.2.1 on 2023-06-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_product_name_uz_product_xarakteristika_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='botuser',
            table='bot_user',
        ),
    ]
