# Generated by Django 4.2.1 on 2023-06-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_remove_botuser_user_id_alter_botuser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='yakunlandi',
            field=models.BooleanField(default=False),
        ),
    ]
